[workspace]
members = [
    "templogd",
    "common",
    "tempgrpcd"
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1"
clap = { version = "4.5", features = ["derive", "env"] }
common = { path = "common" }
json-subscriber = "0.2"
mockall = "0.14"
redis = { version = "1.2", features = ["connection-manager", "tokio-comp", "streams"] }
reqwest = { version = "0.13", default-features = false, features = ["blocking", "json", "rustls"] }
scopeguard = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tokio = { version = "1.47", features = ["full"] }
tokio-util = "0.7"
tracing = "0.1"

[profile.release]
opt-level = "z"
debug = false
lto = true
overflow-checks = true
codegen-units = 1
panic = "abort"
strip = true
