[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
nix = { version = "0.28.0", features = ["fs"] }
redis = { version = "0.25", features = ["connection-manager", "tokio-comp", "streams"] }
syslog = "6.1"

[build-dependencies]
