[package]
name = "common"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
chrono = "0.4"
cfg-if = "1.0"
nix = { version = "0.30", features = ["fs"] }
redis = { version = "0.32", features = ["connection-manager", "tokio-comp", "streams"] }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
scopeguard = "1.2"
serde_json = { version = "1.0" }
syslog = "7.0"
tokio = { version = "1.47", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
httpmock = "0.7"
mockall = { version = "0.13" }
mockall_double = { version = "0.3" }
tokio = { version = "1.47", features = ["full"] }
