[package]
name = "common"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
chrono = "0.4"
cfg-if = "1.0"
nix = { version = "0.30", features = ["fs"] }
redis = { workspace = true }
reqwest = { workspace = true }
scopeguard = { workspace = true }
serde_json = { workspace = true }
syslog = "7.0"
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
httpmock = "0.7"
mockall = { workspace = true }
mockall_double = { version = "0.3" }
tokio = { workspace = true }
